import type { TemplateTheme } from "@/types";

export const TEMPLATES: TemplateTheme[] = [
  {
    id: "a3-brand",
    name: "A3 Brand",
    tagline: "Data-driven dealership social, A3 voice",
    category: "Dealership",
    palette: {
      bg: "#0B0D0F",
      surface: "#2C3038",
      text: "#FFFFFF",
      muted: "#8A919C",
      accent: "#1DB954",
      accent2: "#FFFFFF",
    },
    fonts: {
      display: '"Sora", system-ui, sans-serif',
      body: '"Sora", system-ui, sans-serif',
    },
    vibe: "bold",
    backdrop: "spotlight",
  },
  {
    // Modeled on the Parks Lincoln of Longwood reference set:
    // serif display, white-on-photo, persistent contact footer,
    // thin outlined frames, italic taglines.
    id: "premium-dealer",
    name: "Premium Dealer",
    tagline: "Editorial dealership posters · Parks Lincoln style",
    category: "Dealership",
    palette: {
      bg: "#0B0D0F",
      surface: "#1A1A1F",
      text: "#FFFFFF",
      muted: "#D6D6D6",
      accent: "#FFFFFF",
      accent2: "#E8DBC8",
    },
    fonts: {
      display: '"Playfair Display", "DM Serif Display", serif',
      body: '"Sora", system-ui, sans-serif',
    },
    vibe: "elegant",
    backdrop: "spotlight",
  },
  {
    id: "luxury-automotive",
    name: "Luxury Automotive",
    tagline: "Performance meets prestige",
    category: "Dealership",
    palette: {
      bg: "#0A0A0B",
      surface: "#141417",
      text: "#FFFFFF",
      muted: "#9CA3AF",
      accent: "#D4AF37",
      accent2: "#1DB954",
    },
    fonts: {
      display: '"Playfair Display", "Sora", serif',
      body: '"Sora", system-ui, sans-serif',
    },
    vibe: "elegant",
    backdrop: "spotlight",
  },
  {
    id: "real-estate",
    name: "Pre-Owned · Editorial",
    tagline: "Show the vehicle, sell the trust",
    category: "Dealership",
    palette: {
      bg: "#F4F1EC",
      surface: "#FFFFFF",
      text: "#1A1A1A",
      muted: "#6B6B6B",
      accent: "#1F4E47",
      accent2: "#C8A56B",
    },
    fonts: {
      display: '"DM Serif Display", "Sora", serif',
      body: '"Sora", system-ui, sans-serif',
    },
    vibe: "elegant",
    backdrop: "gradient",
  },
  {
    id: "fitness",
    name: "Fitness",
    tagline: "Push the limits",
    category: "Health",
    palette: {
      bg: "#0E0E10",
      surface: "#1A1A1F",
      text: "#FFFFFF",
      muted: "#A1A1AA",
      accent: "#FF3B3B",
      accent2: "#FFD60A",
    },
    fonts: {
      display: '"Sora", system-ui, sans-serif',
      body: '"Sora", system-ui, sans-serif',
    },
    vibe: "energetic",
    backdrop: "scanlines",
  },
  {
    id: "fashion",
    name: "Fashion",
    tagline: "Editorial. Effortless. Elevated.",
    category: "Lifestyle",
    palette: {
      bg: "#FFFFFF",
      surface: "#F7F5F2",
      text: "#0B0B0B",
      muted: "#7A7A7A",
      accent: "#0B0B0B",
      accent2: "#E8B4B8",
    },
    fonts: {
      display: '"Playfair Display", serif',
      body: '"Sora", system-ui, sans-serif',
    },
    vibe: "minimal",
    backdrop: "noise",
  },
  {
    id: "ai-startup",
    name: "AI Startup",
    tagline: "Ship the future",
    category: "Tech",
    palette: {
      bg: "#06070A",
      surface: "#0E1119",
      text: "#FFFFFF",
      muted: "#94A3B8",
      accent: "#7C3AED",
      accent2: "#22D3EE",
    },
    fonts: {
      display: '"Space Grotesk", "Sora", sans-serif',
      body: '"Inter", system-ui, sans-serif',
    },
    vibe: "bold",
    backdrop: "mesh",
  },
  {
    id: "corporate",
    name: "Corporate",
    tagline: "Trusted. Strategic. Clear.",
    category: "Business",
    palette: {
      bg: "#FFFFFF",
      surface: "#F8FAFC",
      text: "#0F172A",
      muted: "#64748B",
      accent: "#0EA5E9",
      accent2: "#1E293B",
    },
    fonts: {
      display: '"Inter", system-ui, sans-serif',
      body: '"Inter", system-ui, sans-serif',
    },
    vibe: "minimal",
    backdrop: "grid",
  },
  {
    id: "dark-minimal",
    name: "Dark Minimal",
    tagline: "Less, but better",
    category: "Editorial",
    palette: {
      bg: "#0B0B0C",
      surface: "#161618",
      text: "#FAFAFA",
      muted: "#71717A",
      accent: "#FAFAFA",
      accent2: "#1DB954",
    },
    fonts: {
      display: '"Sora", system-ui, sans-serif',
      body: '"Sora", system-ui, sans-serif',
    },
    vibe: "minimal",
    backdrop: "noise",
  },
  {
    id: "futuristic-neon",
    name: "Futuristic Neon",
    tagline: "Glow up the feed",
    category: "Tech",
    palette: {
      bg: "#04040A",
      surface: "#0A0A14",
      text: "#FFFFFF",
      muted: "#A5B4FC",
      accent: "#22D3EE",
      accent2: "#F472B6",
    },
    fonts: {
      display: '"Space Grotesk", "Sora", sans-serif',
      body: '"Space Grotesk", "Sora", sans-serif',
    },
    vibe: "neon",
    backdrop: "mesh",
  },
];

export function getTemplate(id: string): TemplateTheme {
  return TEMPLATES.find((t) => t.id === id) ?? TEMPLATES[0];
}
